# Generated by Django 5.0.6 on 2024-05-26 04:40

import django.db.models.deletion
import wesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=wesapp.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hall_image', models.ImageField(upload_to=wesapp.models.getFileName)),
                ('old_price', models.IntegerField(blank=True, null=True)),
                ('dis_price', models.IntegerField()),
                ('adress', models.TextField(max_length=500)),
                ('handpicked', models.BooleanField(default=False, help_text='0-defaul,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wesapp.wedding')),
            ],
        ),
    ]
