# Generated by Django 5.0.6 on 2024-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='status',
            field=models.BooleanField(default=False, help_text='0-defaul,1-Hidden'),
        ),
        migrations.AlterField(
            model_name='traditional',
            name='handpicked',
            field=models.BooleanField(default=False, help_text='0-defaul,1-Trending'),
        ),
    ]
