# Generated by Django 5.0.6 on 2024-05-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0002_wedding_status_alter_traditional_handpicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='traditional',
            name='status',
            field=models.BooleanField(default=False, help_text='0-defaul,1-Hidden'),
        ),
    ]
