# Generated by Django 5.0.6 on 2024-06-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0005_alter_cart_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='hall',
            new_name='product',
        ),
    ]
