# Generated by Django 5.0.6 on 2024-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0006_rename_hall_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
