# Generated by Django 5.0.6 on 2024-06-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0012_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
