# Generated by Django 5.0.6 on 2024-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wesapp', '0014_order_odrderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phno',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
